services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www # Mount the app code
      - vendor:/var/www/vendor # Named volume for vendor
      - storage:/var/www/storage # Named volume for storage
      - bootstrap_cache:/var/www/bootstrap/cache # Named volume for bootstrap/cache
    env_file:
      - .env # Automatically loads environment variables from .env file
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:
  vendor: # Volume for vendor directory
  storage: # Volume for storage directory
  bootstrap_cache: # Volume for bootstrap/cache directory

networks:
  app-network:
    driver: bridge
